name: Manually trigger an Azure Machine Learning job

on:
  pull_request:

env:
  workspace-name: mlw-dp100-lb152eb03e5604ef2af # name of the Azure Machine Learning workspace
  resource-group: rg-dp100-lb152eb03e5604ef2af # name of the Azure resource group

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml --workspace-name ${{ env.workspace-name }} --resource-group ${{ env.resource-group }}


